name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Download and Install MPJ JAR
      run: |
        wget https://sourceforge.net/projects/mpjexpress/files/releases/mpj-v0_44.zip/download -O mpj-v0_44.zip
        unzip mpj-v0_44.zip -d mpj
        mvn install:install-file -Dfile=mpj/mpj-v0_44/lib/mpj.jar -DgroupId=com.googlecode.mpj-express -DartifactId=mpj-v0_44 -Dversion=0.44 -Dpackaging=jar

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests with Maven
      run: mvn test --file pom.xml

    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@v1
